// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMIQpZx0N8vAo1Oqw2I1OSR-sZR-cKDII',
    appId: '1:643236272873:android:2c497bb2ce05f42a67ae78',
    messagingSenderId: '643236272873',
    projectId: 'digi-farmer-364606',
    storageBucket: 'digi-farmer-364606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRcroPZAzEjmDpL54z-5K_Ug2LckJay_Y',
    appId: '1:643236272873:ios:c3d2f74663f89a3467ae78',
    messagingSenderId: '643236272873',
    projectId: 'digi-farmer-364606',
    storageBucket: 'digi-farmer-364606.appspot.com',
    androidClientId: '643236272873-c329tbvepuuu23urpvup5nvcoo76bgjk.apps.googleusercontent.com',
    iosClientId: '643236272873-qek5ng0ohg7abig4ane7rlp0b09frocg.apps.googleusercontent.com',
    iosBundleId: 'com.example.digiFarmer',
  );
}
